export const MovieGenreList = [
  {
    name: 'drama',
    cssClass: 'g1',
    isIcon: true,
    iconName: 'heart',
    color: '#ffd100',
  },
  {
    name: 'comedy',
    cssClass: 'g2',
    isIcon: false,
    imgPath: 'assets/icon/clown.png',
    color: '#ff9100',
  },
  {
    name: 'survival',
    cssClass: 'g3',
    isIcon: true,
    iconName: 'skull',
    color: '#00b3b7',
  },
  {
    name: 'crime',
    cssClass: 'g4',
    isIcon: false,
    imgPath: 'assets/icon/thief.png',
    color: '#ffaeae',
  },
  {
    name: 'kids',
    cssClass: 'g5',
    isIcon: true,
    iconName: 'accessibility',
    color: '#00dfc0',
  },
  {
    name: 'mystery',
    cssClass: 'g6',
    isIcon: false,
    imgPath: 'assets/icon/mystery.png',
    color: '#e552fff0',
  },
  {
    name: 'war',
    cssClass: 'g7',
    isIcon: false,
    imgPath: 'assets/icon/sword.png',
    color: '#17e760',
  },
  {
    name: 'action',
    cssClass: 'g8',
    isIcon: false,
    imgPath: 'assets/icon/action.png',
    color: '#c7c121',
  },
  {
    name: 'horror',
    cssClass: 'g9',
    isIcon: false,
    imgPath: 'assets/icon/ghost.png',
    color: '#477df5f0',
  },
  {
    name: 'historical',
    cssClass: 'g10',
    isIcon: false,
    imgPath: 'assets/icon/helmet.png',
    color: '#11def3fa',
  },
  {
    name: 'science',
    cssClass: 'g11',
    isIcon: true,
    iconName: 'logo-electron',
    color: '#fd6538',
  },
  {
    name: 'fantasy',
    cssClass: 'g12',
    isIcon: false,
    imgPath: 'assets/icon/dragon.png',
    color: '#49cd13f5',
  },
];
